"""
    Contains all information about a single participant of a given match.
"""


class Participant:
    def __init__(self, p):
        iterator = iter(p)
        self.participant_db_id = next(iterator)
        self.match_id = next(iterator)
        self.all_in_pings = next(iterator)
        self.assists = next(iterator)
        self.baron_kills = next(iterator)
        self.bounty_level = next(iterator)
        self.champ_experience = next(iterator)
        self.champ_level = next(iterator)
        self.champion_id = next(iterator)
        self.champion_name = next(iterator)
        self.champion_transform = next(iterator)
        self.consumables_purchased = next(iterator)
        self.damage_dealt_to_buildings = next(iterator)
        self.damage_dealt_to_objectives = next(iterator)
        self.damage_dealt_to_turrets = next(iterator)
        self.damage_self_mitigated = next(iterator)
        self.danger_pings = next(iterator)
        self.deaths = next(iterator)
        self.detector_wards_placed = next(iterator)
        self.double_kills = next(iterator)
        self.dragon_kills = next(iterator)
        self.eligible_for_progression = next(iterator)
        self.enemy_missing_pings = next(iterator)
        self.first_blood_assist = next(iterator)
        self.first_blood_kill = next(iterator)
        self.first_tower_assist = next(iterator)
        self.first_tower_kill = next(iterator)
        self.game_ended_in_early_surrender = next(iterator)
        self.game_ended_in_surrender = next(iterator)
        self.get_back_pings = next(iterator)
        self.gold_earned = next(iterator)
        self.gold_spent = next(iterator)
        self.hold_pings = next(iterator)
        self.individual_position = next(iterator)
        self.inhibitor_kills = next(iterator)
        self.inhibitor_takedowns = next(iterator)
        self.inhibitors_lost = next(iterator)
        self.item0 = next(iterator)
        self.item1 = next(iterator)
        self.item2 = next(iterator)
        self.item3 = next(iterator)
        self.item4 = next(iterator)
        self.item5 = next(iterator)
        self.item6 = next(iterator)
        self.items_purchased = next(iterator)
        self.killing_sprees = next(iterator)
        self.kills = next(iterator)
        self.lane = next(iterator)
        self.largest_critical_strike = next(iterator)
        self.largest_killing_spree = next(iterator)
        self.largest_multi_kill = next(iterator)
        self.longest_time_spent_living = next(iterator)
        self.magic_damage_dealt = next(iterator)
        self.magic_damage_dealt_to_champions = next(iterator)
        self.magic_damage_taken = next(iterator)
        self.neutral_minions_killed = next(iterator)
        self.nexus_kills = next(iterator)
        self.nexus_takedowns = next(iterator)
        self.nexus_lost = next(iterator)
        self.objectives_stolen = next(iterator)
        self.objectives_stolen_assists = next(iterator)
        self.participant_id = next(iterator)
        self.penta_kills = next(iterator)
        self.perk_defense = next(iterator)
        self.perk_flex = next(iterator)
        self.perk_offense = next(iterator)
        self.physical_damage_dealt = next(iterator)
        self.physical_damage_dealt_to_champions = next(iterator)
        self.physical_damage_taken = next(iterator)
        self.placement = next(iterator)
        self.player_augment1 = next(iterator)
        self.player_augment2 = next(iterator)
        self.player_augment3 = next(iterator)
        self.player_augment4 = next(iterator)
        self.player_subteam_id = next(iterator)
        self.profile_icon = next(iterator)
        self.push_pings = next(iterator)
        self.puuid = next(iterator)
        self.quadra_kills = next(iterator)
        self.riot_id_game_name = next(iterator)
        self.riot_id_name = next(iterator)
        self.riot_id_tag_line = next(iterator)
        self.role = next(iterator)
        self.sight_wards_bought_in_game = next(iterator)
        self.spell1_casts = next(iterator)
        self.spell2_casts = next(iterator)
        self.spell3_casts = next(iterator)
        self.spell4_casts = next(iterator)
        self.summoner1_casts = next(iterator)
        self.summoner1_id = next(iterator)
        self.summoner2_casts = next(iterator)
        self.summoner2_id = next(iterator)
        self.summoner_id = next(iterator)
        self.summoner_level = next(iterator)
        self.summoner_name = next(iterator)
        self.team_early_surrendered = next(iterator)
        self.team_id = next(iterator)
        self.team_position = next(iterator)
        self.time_ccing_others = next(iterator)
        self.time_played = next(iterator)
        self.total_ally_jungle_minions_killed = next(iterator)
        self.total_damage_dealt = next(iterator)
        self.total_damage_dealt_to_champions = next(iterator)
        self.total_damage_shielded_on_teammates = next(iterator)
        self.total_damage_taken = next(iterator)
        self.total_heal = next(iterator)
        self.total_heals_on_teammates = next(iterator)
        self.total_minions_killed = next(iterator)
        self.total_time_cc_dealt = next(iterator)
        self.total_time_spent_dead = next(iterator)
        self.total_units_healed = next(iterator)
        self.triple_kills = next(iterator)
        self.true_damage_dealt = next(iterator)
        self.true_damage_dealt_to_champions = next(iterator)
        self.true_damage_taken = next(iterator)
        self.turret_kills = next(iterator)
        self.turret_takedowns = next(iterator)
        self.turrets_lost = next(iterator)
        self.unreal_kills = next(iterator)
        self.vision_score = next(iterator)
        self.vision_wards_bought_in_game = next(iterator)
        self.wards_killed = next(iterator)
        self.wards_placed = next(iterator)
        self.win = next(iterator)


    def __str__(self):
        str = f"""participant_db_id: {self.participant_db_id}
match_id: {self.match_id}
all_in_pings: {self.all_in_pings}
assists: {self.assists}
baron_kills: {self.baron_kills}
bounty_level: {self.bounty_level}
champ_experience: {self.champ_experience}
champ_level: {self.champ_level}
champion_id: {self.champion_id}
champion_name: {self.champion_name}
champion_transform: {self.champion_transform}
consumables_purchased: {self.consumables_purchased}
damage_dealt_to_buildings: {self.damage_dealt_to_buildings}
damage_dealt_to_objectives: {self.damage_dealt_to_objectives}
damage_dealt_to_turrets: {self.damage_dealt_to_turrets}
damage_self_mitigated: {self.damage_self_mitigated}
danger_pings: {self.danger_pings}"""
        return str
